name: CI

on:
  merge_group:
    types: [checks_requested]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "website/**"
    tags-ignore:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

permissions:
  # Allow commenting on issues for `reusable-build.yml`
  issues: write

jobs:
  get-runner-labels:
    name: Get Runner Labels
    uses: ./.github/workflows/get-runner-labels.yml

  test-linux:
    name: Test Linux
    needs: [get-runner-labels]
    uses: ./.github/workflows/reusable-build.yml
    with:
      target: x86_64-unknown-linux-gnu
      runner: ${{ needs.get-runner-labels.outputs.LINUX_RUNNER_LABELS }}
      skipable: false
      bench: false
      full-install: false
